Repository soosora/kosmicengine, pull requests merged in 2025-02, with the labels that each got.

#2 fix: stb_image not found during compilation
  Engine/CMakeLists.txt
  Engine/src/Renderer/Texture.cpp
Labels: bug

#3 feat(assimp): static compilation
  Thirdparty/CMakeLists.txt
Labels: enhancement

#5 fix: spdlog header & feat: use ccache
  CMakeLists.txt
  Engine/CMakeLists.txt
  Sandbox/CMakeLists.txt
  Thirdparty/CMakeLists.txt
Labels: bug, enhancement

#4 feat(ci): add a github actions to check if your code is compile on a different machine :P
  .github/workflows/cmake-multi-platform.yml
  Docs/pt_BR/README.md
  README.md
Labels: enhancement
